---
title: ""
toc: false
image: logo-com-fundo.svg
about:
    template: jolla
    image-width: 22em
    image-shape: rounded
---

# Quem Somos?

---

O MECAPLAB é um laboratório da Universidade Federal da Paraíba. **Fundado em 1998**, o laboratório está vinculado ao curso de administração do **Campus III da UFPB** e vem realizando projetos relacionados à gestão de negócios, finanças empresariais e pessoais, análises de políticas econômicas, estudos sobre mobilidade urbana e pesquisas sobre mercado financeiro. Atualmente, o MECAPLAB está sob responsabilidade dos docentes Gustavo Correia Xavier e Claudio Germano, no qual ambos vem colaborando juntos diversos projetos juntamente com discentes de Administração no Campus III da UFPB.

---

## Responsáveis Pelo MECAP.LAB

## Equipe de Estagiários (2024)

## Premiações

## Entre em contato

O Laboratório recebe novos pesquisadores a cada semestre ao longo do período letivo da UFPB e desenvolve projetos de pesquisa acadêmica, ações de capacitação profissional, desenvolvimento de produtos para o setor privado, bem como desenvolve pesquisa em parcerias com entes externos do setor público e privado.

